tap "homebrew/bundle"
tap "homebrew/cask", "https://mirrors.ustc.edu.cn/homebrew-cask.git"
tap "homebrew/core", "https://mirrors.ustc.edu.cn/homebrew-core.git"
tap "homebrew/services", "https://gitee.com/cunkai/homebrew-services.git"
tap "romkatv/powerlevel10k"

brew "exa"
brew "bat"
brew "fzf"
brew "gh"
brew "python@3.9"
brew "macvim"
brew "nnn"
brew "shellcheck"
brew "tldr"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-vi-mode"
brew "romkatv/powerlevel10k/powerlevel10k"
