#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="${BASEDIR}/legacy-dotbot/install.conf.yaml"
DOTBOT_DIR="${BASEDIR}/legacy-dotbot/dotbot"
DOTBOT_BIN="${DOTBOT_DIR}/bin/dotbot"

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git -C "${BASEDIR}" submodule update --init --recursive legacy-dotbot/dotbot

"${DOTBOT_BIN}" -d "${BASEDIR}/legacy-dotbot" -c "${CONFIG}" "${@}"
